name: CloudFormation Linter

on:
  pull_request:
    branches: [disabled]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cfn-lint
        uses: scottbrenner/cfn-lint-action@v2

      - name: Run cfn-lint
        run: cfn-lint -t ./stack.yaml
