name: Go Push Lib

on:
  workflow_call:

jobs:
  go-push-lib:
    runs-on: ubuntu-latest

    steps:
      - name: Generate a token for release-please
        id: release-please-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.RELEASE_PLEASE_CLIENT_ID }}
          private-key: ${{ secrets.APP_RELEASE_PLEASE_PK }}

      - uses: googleapis/release-please-action@v5
        with:
          token: ${{ steps.release-please-token.outputs.token }}
          release-type: go
