name: TS Worker Linter

on:
  pull_request:
    branches: [disabled]

jobs:
  ts-worker-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download official ESLint configuration
        run: curl -fo eslint.config.mjs https://raw.githubusercontent.com/Fundamentarium/.github-workflows/main/eslint.config.worker.mjs

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .
